version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/prod-
hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
