name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          # Connect to EC2 instance and run deployment commands
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Deploying application..."

            # Navigate to the project directory
            cd /home/ubuntu/prod-

            # Pull the latest changes from your repository
            git pull origin main

            # Install dependencies
            npm install

            # Build the application (if applicable)
            npm run build

            # Restart pm2
            pm2 restart 0

            echo "Deployment completed!"
          EOF
